From docker.sas.com/honxin/r-base:latest
MAINTAINER Hongjie Xin <Hongjie.xin@sas.com>
LABEL docker image with embedded R model

COPY *.zip /pybox/model

#ENTRYPOINT ["/bin/bash"]
ENTRYPOINT ["/bin/bash", "startServer.sh"]


