From docker.sas.com/honxin/pyml-base:latest
MAINTAINER Hongjie Xin <Hongjie.xin@sas.com>
LABEL docker image with embedded python model

COPY *.zip /pybox/model

#ENTRYPOINT ["/bin/bash"]
ENTRYPOINT ["/bin/bash", "startServer.sh"]


